version: '3'
services:
  voice-converter:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - MODEL_PATH=/app/models
